Seems like conda's macOS build env doesn't have `HAVE_CLOCK_GETTIME` / `CLOCK_REALTIME`
Fixes `pytime.c:601:25: error: use of undeclared identifier  'CLOCK_REALTIME'
err = clock_gettime(CLOCK_REALTIME, &ts);